services:
  app:
    build: .
    container_name: lks2025cc-backend
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=user:password@tcp(aws-rds-endpoint:3306)/golang_db?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_ADDR=aws-redis-endpoint:6379
      - AWS_REGION=us-east-1
      - AWS_BUCKET_NAME=your-bucket-name
      - AWS_ACCESS_KEY=your-access-key
      - AWS_SECRET_KEY=your-secret-key
